### ISSUE TITLE
Extend program features if possible or any ideas come up

### ISSUE THREAD

**Issue by tylerkj1209** [CSC207-2022F-UofT/course-project-mewdy#43]
If you have a creative idea to better match the user stories we came up with or implement a new feature to the code please comment on this issue.

**Comment by Wizard603** [comment]
We could add goals to the metrics. And tell the user what percentage of their logged data meets the goal.

**Comment by Wizard603** [comment]
We have decided to add Goal tracking as a extended feature and will explore darkmode if time permits
